## Section 10.1

## Question 1: Understanding the Split-Apply-Combine Mechanics

Given the following DataFrame representing a small sales team:
```python
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'South', 'West', 'South'],
    'Sales': [100, 250, 150, 300, 200, 50],
    'Expenses': [80, 200, 120, 250, 150, 40]
})
```
1. Write a single line of code to calculate the **mean** Sales for each **Region**.
2. Explain in your own words what the "Split" and "Apply" steps are doing specifically for the 'East' region in this calculation.

In [ ]:
# Type your solution here:

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'South', 'West', 'South'],
    'Sales': [100, 250, 150, 300, 200, 50],
    'Expenses': [80, 200, 120, 250, 150, 40]
})

regional_mean = df.groupby('Region').mean()
regional_mean

# Split and apply are two steps in the groupby process. They are doing the following for the East region: They are splitting the data into groups based on the 'Region' column, and then applying the mean function to calculate the average Sales and Expenses for each region. The result is a new DataFrame that shows the average Sales and Expenses for each region.

        Sales  Expenses
Region
East    125.0     100.0
South   175.0     145.0
West    225.0     175.0


## Question 2: Grouping by External Arrays

Using the same `df` from Question 1, assume we want to group the data based on whether the performance was "High" or "Low" using an external list:
```python
performance_tier = ['Low', 'High', 'Low', 'High', 'High', 'Low']
```
1. Use the `performance_tier` list to group the `df` and calculate the **total (sum)** of both Sales and Expenses.
2. **True or False:** The resulting index of your new DataFrame will contain the names of the Regions (East, West, South). Explain why or why not.

In [4]:
# Type your solution here:

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'South', 'West', 'South'],
    'Sales': [100, 250, 150, 300, 200, 50],
    'Expenses': [80, 200, 120, 250, 150, 40]
})

performance_tier = ['Low', 'High', 'Low', 'High', 'High', 'Low']

df['Performance'] = performance_tier
performances = df.groupby('Performance' \
                          '').sum()
performances

                    Region  Sales  Expenses
Performance
High         WestSouthWest    750       600
Low          EastEastSouth    300       240

## Section 10.2

### Question 1: Single Grouping and Column Selection
**Scenario:** You have a DataFrame representing a small sales team.
```python
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'City': ['New York', 'London', 'London', 'New York', 'New York'],
    'Item': ['Laptop', 'Laptop', 'Tablet', 'Tablet', 'Laptop'],
    'Sales': [1200, 950, 450, 500, 1150],
    'Quantity': [1, 1, 2, 1, 2]
})
```
**Task:** 1. Group the data by `City`.
2. Calculate the **mean** for the `Sales` column only.
3. **Goal:** Understand how to index a GroupBy object to avoid calculating means for irrelevant columns (like `Quantity`).

**Expected Solution:**
```python
# Students should identify that data.groupby('City')['Sales'].mean() 
# is more efficient than calculating the mean for the whole DF.
result = data.groupby('City')['Sales'].mean()
print(result)
```

In [9]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'City': ['New York', 'London', 'London', 'New York', 'New York'],
    'Item': ['Laptop', 'Laptop', 'Tablet', 'Tablet', 'Laptop'],
    'Sales': [1200, 950, 450, 500, 1150],
    'Quantity': [1, 1, 2, 1, 2]
})

sales_mean = data.groupby('City')[['Sales']].mean()
sales_mean

          Sales
City
London    700.0
New York  950.0

### Question 2: Grouping with Multiple Keys
**Scenario:** Using the same `data` DataFrame from Question 1.
**Task:**
1. Group the data by both `City` **and** `Item`.
2. Calculate the **total sum** of `Sales`.
3. **Goal:** Understand how passing a list of keys creates a Hierarchical Index (MultiIndex) in the resulting Series.

**Expected Solution:**
```python
# Students practice passing a list as the grouping key
result = data.groupby(['City', 'Item'])['Sales'].sum()
print(result)

# Bonus question for class discussion: 
# "What is the index of the resulting object?"
```

In [ ]:
# Type your solution here:

import pandas as pd
import numpy as np 

data = pd.DataFrame({
    'City': ['New York', 'London', 'London', 'New York', 'New York'],
    'Item': ['Laptop', 'Laptop', 'Tablet', 'Tablet', 'Laptop'],
    'Sales': [1200, 950, 450, 500, 1150],
    'Quantity': [1, 1, 2, 1, 2]
})

grouped_data = data.groupby(['City', 'Item'])[['Sales']].sum()
grouped_data

City      Item
London    Laptop     950
          Tablet     450
New York  Laptop    2350
          Tablet     500
Name: Sales, dtype: int64

## Section 10.3

## Question 1: Group-Level Top-N Analysis

Suppose you have a DataFrame of sales data with columns `['Region', 'Salesperson', 'Revenue']`. Write a function called `top_sales` that takes a group and returns the rows containing the **top 2** highest `Revenue` values. Then, group the DataFrame by `Region` and use `.apply()` to see the top performers in every region.

**Data Setup for Students:**
```python
import pandas as pd

data = pd.DataFrame({
    'Region': ['East', 'East', 'East', 'West', 'West', 'West', 'South', 'South'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Edward', 'Frank', 'Guy', 'Helen'],
    'Revenue': [500, 700, 600, 300, 800, 450, 900, 1000]
})
```

In [ ]:
# Type your solution here:

import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Region': ['East', 'East', 'East', 'West', 'West', 'West', 'South', 'South'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Edward', 'Frank', 'Guy', 'Helen'],
    'Revenue': [500, 700, 600, 300, 800, 450, 900, 1000]
})

# Define the custom function
def top_sales(group):
    return group.nlargest(2, 'Revenue')

top_performers = data.groupby('Region', group_keys=False).apply(top_sales)

top_performers

  Salesperson  Revenue
1         Bob      700
2     Charlie      600
7       Helen     1000
6         Guy      900
4      Edward      800
5       Frank      450

## Question 2: Group-Specific Normalization
**Objective:** Understand how to perform "Broadcast" operations within groups (Standardization).

Using the same sales data, you need to compare performance relative to the group average. Write a function that **normalizes** the `Revenue` within each group using the following formula:
$$Revenue_{norm} = \frac{Revenue - \text{mean}}{\text{std}}$$
Apply this function to each `Region` so that students can see which salesperson outperformed their specific regional average.

In [5]:
# Type your solution here:

import pandas as pd

data = pd.DataFrame({
    'Region': ['East', 'East', 'East', 'West', 'West', 'West', 'South', 'South'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Edward', 'Frank', 'Guy', 'Helen'],
    'Revenue': [500, 700, 600, 300, 800, 450, 900, 1000]
})

def normalize_revenue(group):
    """Normalizes the Revenue column within a specific group."""
    avg = group['Revenue'].mean()
    std_dev = group['Revenue'].std()
    
    group['Normalized_Revenue'] = (group['Revenue'] - avg) / std_dev
    return group

#Group the data by 'Region' and apply the normalization function to each group
normalized_data = data.groupby('Region', group_keys=False).apply(normalize_revenue)
normalized_data

  Salesperson  Revenue  Normalized_Revenue
0       Alice      500           -1.000000
1         Bob      700            1.000000
2     Charlie      600            0.000000
3       David      300           -0.844441
4      Edward      800            1.104269
5       Frank      450           -0.259828
6         Guy      900           -0.707107
7       Helen     1000            0.707107

### Question 1: The `transform` Method

You have a DataFrame of student grades from different departments. Create a new column called `deviance` that calculates how much each student's score differs from their **department's average score**.

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'dept': ['CS', 'CS', 'Math', 'Math', 'CS'],
    'score': [85, 95, 70, 80, 75]
})

# Your code here:
# 1. Group by 'dept'
# 2. Use .transform() to subtract the group mean from the 'score' column
```

In [2]:
# Type your solution here:

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'dept': ['CS', 'CS', 'Math', 'Math', 'CS'],
    'score': [85, 95, 70, 80, 75]
})

# Calculate the mean for each department and subtract it from the original score
df['deviance'] = df['score'] - df.groupby('dept')['score'].transform('mean')
df

   dept  score  deviance
0    CS     85       0.0
1    CS     95      10.0
2  Math     70      -5.0
3  Math     80       5.0
4    CS     75     -10.0

### Question 2: The `apply` Method (General Purpose)

Write a function called `top_two` that takes a group and returns the rows with the two highest scores. Apply this function to the DataFrame to see the top performers in each department.

```python
def top_two(group):
    return group.sort_values(by='score', ascending=False)[:2]

# Your code here:
# Use groupby on 'dept' and apply the top_two function
```

In [3]:
# Type your solution here:

import pandas as pd

df = pd.DataFrame({
    'dept': ['CS', 'CS', 'Math', 'Math', 'CS'],
    'score': [85, 95, 70, 80, 75]
})

# Define the function
def top_two(group):
    return group.sort_values(by='score', ascending=False)[:2]

# Group by 'dept' and apply the function
top_performers = df.groupby('dept', group_keys=False).apply(top_two)

top_performers

   score
1     95
0     85
3     80
2     70

## Section 10.5

## Exercise 1: The `transform` Method

You are given a DataFrame of employee salaries across different departments. Write a Python snippet using `groupby` and `transform` to create a new column called `deviation`. This column should show the difference between each employee's salary and the **mean salary of their specific department**.

```python
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Dept': ['HR', 'HR', 'IT', 'IT', 'IT', 'Sales'],
    'Salary': [50000, 60000, 70000, 80000, 90000, 55000]
})

# Your code here:
```

In [4]:
# Type your solution here:

import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Dept': ['HR', 'HR', 'IT', 'IT', 'IT', 'Sales'],
    'Salary': [50000, 60000, 70000, 80000, 90000, 55000]
})

data['deviation'] = data['Salary'] - data.groupby('Dept')['Salary'].transform('mean')
data

    Dept  Salary  deviation
0     HR   50000    -5000.0
1     HR   60000     5000.0
2     IT   70000   -10000.0
3     IT   80000        0.0
4     IT   90000    10000.0
5  Sales   55000        0.0

## Exercise 2: Group-wise Function Application with `apply`

Using the same `data` DataFrame from Exercise 1, write a function that selects the **top N** highest-paid employees in each department. Then, use the `groupby` and `apply` method to return a DataFrame containing the top 1 salary for every department.

```python
def top_salary(df, n=1):
    return df.sort_values(by='Salary', ascending=False)[:n]

# Your code here:
```

In [5]:
# Type your solution here:

import pandas as pd

data = pd.DataFrame({
    'Dept': ['HR', 'HR', 'IT', 'IT', 'IT', 'Sales'],
    'Salary': [50000, 60000, 70000, 80000, 90000, 55000]
})

# Define the function to sort and slice the top 'n' rows
def top_salary(df, n=1):
    return df.sort_values(by='Salary', ascending=False)[:n]

# Group by 'Dept' and apply the function, passing n=1 as an argument
top_earners = data.groupby('Dept', group_keys=False).apply(top_salary, n=1)
top_earners

   Salary
1   60000
4   90000
5   55000