## Section 8.1

### **Practice Problem 1: Creating and Accessing a MultiIndex Series**

**Objective:** Understand how to create and index a `MultiIndex` Series.

**Task:**
You are given the following data representing sales:

* Store A, Day 1 → 100
* Store A, Day 2 → 120
* Store B, Day 1 → 90
* Store B, Day 2 → 110

**Instructions:**

1. Create a pandas `Series` using a **MultiIndex** with levels: `Store` and `Day`.
2. Assign appropriate names to the index levels.
3. Perform the following:

   * Retrieve all sales for **Store A**
   * Retrieve sales for **Day 1 across all stores**

**Expected Learning Outcomes:**

* Creating a MultiIndex from arrays/tuples
* Naming index levels
* Partial indexing (selection by one level)

In [19]:
# Type your solution here:
import numpy as np
import pandas as pd

index = pd.MultiIndex.from_tuples(
    [('Store A', 'Day 1'), 
     ('Store A', 'Day 2'),
     ('Store B', 'Day 1'), 
     ('Store B', 'Day 2')],
    names=['Store', 'Day']
) 

sales = pd.Series([100, 120, 90, 110], index=index)
print("Sales Series")
print(sales)
print()

store_a_sales = sales.loc ['Store A']
print('Sales for Store A')
print(store_a_sales)
print()

day1_sales = sales[sales.index.get_level_values('Day') == 'Day 1']
print('Day 1 Sales')
day1_sales

Sales Series
Store    Day
Store A  Day 1    100
         Day 2    120
Store B  Day 1     90
         Day 2    110
dtype: int64

Sales for Store A
Day
Day 1    100
Day 2    120
dtype: int64

Day 1 Sales

Store    Day
Store A  Day 1    100
Store B  Day 1     90
dtype: int64

### **Practice Problem 2: Reshaping with MultiIndex (Unstacking)**

**Objective:** Learn how to reshape hierarchical data.

**Task:**
Using the same dataset from Problem 1:

1. Convert the MultiIndex `Series` into a **DataFrame** where:

   * Rows = Stores
   * Columns = Days
2. Then:

   * Fill any missing values with 0 (if applicable)
   * Compute total sales per store

**Expected Learning Outcomes:**

* Using `.unstack()` to reshape data
* Understanding row/column alignment
* Performing simple aggregation after reshaping

In [18]:
# Type your solution here:
import pandas as pd
import numpy as np

index = pd.MultiIndex.from_tuples(
    [('Store A', 'Day 1'), 
     ('Store A', 'Day 2'),
     ('Store B', 'Day 1'), 
     ('Store B', 'Day 2')],
    names=['Store', 'Day']
) 

sales = pd.Series([100, 120, 90, 110], index=index)

sales_df = sales.unstack(level='Day')
print(sales_df)
print()

store_totals = sales_df.sum(axis=1)
print('Total Store Sales')
store_totals

Day      Day 1  Day 2
Store
Store A    100    120
Store B     90    110

Total Store Sales

Store
Store A    220
Store B    200
dtype: int64

## Section 8.2 

### Problem 1: The "Store Manager" (Merging)
**Goal:** Use `pd.merge` to combine product information with sales data.

**The Scenario:** You have two small DataFrames. One contains a list of `product_id`s and their names. The other contains `product_id`s and the quantity sold. Notice that some products haven't sold any units yet.

**Task:** Perform an **inner join** to see only the products that have sales data. Then, try a **left join** to see all products, even those with no sales (which will appear as `NaN`).

In [17]:
# Type your solution here:

import pandas as pd

products = pd.DataFrame({
    'product_id': [101, 102, 103, 104],
    'name': ['Laptop', 'Mouse', 'Monitor', 'Keyboard']
})

sales = pd.DataFrame({
    'product_id': [101, 102, 101, 103],
    'quantity': [1, 5, 2, 2]
})

product_sales = pd.merge(products,sales)
print('Inner Merge')
print(product_sales)
print()

left_pd = pd.merge(products, sales, how="left")
print('Left Merge')
left_pd

Inner Merge
   product_id     name  quantity
0         101   Laptop         1
1         101   Laptop         2
2         102    Mouse         5
3         103  Monitor         2

Left Merge

   product_id      name  quantity
0         101    Laptop       1.0
1         101    Laptop       2.0
2         102     Mouse       5.0
3         103   Monitor       2.0
4         104  Keyboard       NaN

### Problem 2: The "Quarterly Report" (Concatenating)
**Goal:** Use `pd.concat` to stack datasets vertically.

**The Scenario:** You have two separate DataFrames representing sales from January and February. They have the exact same columns. You need to combine them into a single "Early Year" report.


**Task:**
1. Use `pd.concat` to combine these two DataFrames into one.
2. Observe the index—it will likely repeat (0, 1, 0, 1). 
3. Re-run the concatenation using the `ignore_index=True` argument to create a clean, continuous index from 0 to 3.

In [16]:
# Type your solution here:
import pandas as pd

jan_sales = pd.DataFrame({
    'item': ['Apple', 'Banana'],
    'revenue': [150, 200]
}, index=[0, 1])

feb_sales = pd.DataFrame({
    'item': ['Orange', 'Apple'],
    'revenue': [120, 180]
}, index=[0, 1])

early_year_report = pd.concat([jan_sales,feb_sales])
print(early_year_report)
print()

early_year_report = pd.concat([jan_sales,feb_sales], ignore_index=True)
early_year_report

     item  revenue
0   Apple      150
1  Banana      200
0  Orange      120
1   Apple      180

     item  revenue
0   Apple      150
1  Banana      200
2  Orange      120
3   Apple      180

## Section 8.3

### Problem 1: The "Stack & Unstack" Swap
**Concept:** Understanding how hierarchical indexing changes when you move an inner level to columns.

**The Scenario:** You have a small Series representing the sales of two fruits across two seasons. The data is currently "long" with a MultiIndex.

**The Task:**
1. Use `.unstack()` to turn the `fruit` index into columns.
2. Use `.stack()` on that result to return it to its original Series format.

**Expected Outcome:** Students should see the data transform from a 1D Series into a 2D DataFrame and back again.

In [ ]:
# Type your solution here:

import pandas as pd
import numpy as np

data = pd.Series(np.random.randint(10, 50, 4),
                index=pd.MultiIndex.from_product([['Summer', 'Winter'], ['Apples', 'Oranges']],
                                                    names=['season', 'fruit']))

print(data)
print()

fruits_unstacked = data.unstack(level = 'fruit')
print(fruits_unstacked)
print()

fruits_restacked = fruits_unstacked.stack(level='fruit')
fruits_restacked

season  fruit
Summer  Apples     23
        Oranges    36
Winter  Apples     20
        Oranges    40
dtype: int64

season  fruit
Summer  Apples     23
        Oranges    36
Winter  Apples     20
        Oranges    40
dtype: int64

### Problem 2: Pivoting from "Long" to "Wide"
**Concept:** Using `pivot` to make data more readable for analysis.

**The Scenario:**
You are given a "melted" (long) dataset of stock prices. It’s hard to compare the stocks because they are all in one column.

**The Task:**
1. Use the `.pivot()` method to reshape the data so that:
   * The **rows** are indexed by `date`.
   * The **columns** are the `item` names (AAPL, GOOG).
   * The **values** are the stock prices.

**Expected Outcome:**
A DataFrame where each row is a single date and each column is a specific stock's price, making it easy to calculate the daily difference between the two.

In [14]:
# Type your solution here:

df = pd.DataFrame({
       'date': ['2026-01-01', '2026-01-01', '2026-01-02', '2026-01-02'],
       'item': ['AAPL', 'GOOG', 'AAPL', 'GOOG'],
       'value': [150, 2800, 155, 2810]
   })

new_df = df.pivot(index="date", columns="item",values="value")
new_df

item        AAPL  GOOG
date
2026-01-01   150  2800
2026-01-02   155  2810